### ISSUE TITLE
Feedback on the Ineffective Volume Adjustment and Error Reporting after Installing

### ISSUE THREAD

**Issue by hyyczz** [pwt/docker-airconnect-arm#17] opened 2024-12-23 07:07 UTC
First of all, I would like to express my gratitude for your hard work on this software.
When installed in Armbian armv7a and Docker, it seems that it can be connected and run. However, no matter how I adjust the volume, there's no way to make the speaker play normally. It can be connected, but there's no sound. I don't know what went wrong. So I checked the log and found that there seemed to be some error messages. Can it be fixed？Thank you.

```
S[06:15:08.826] main:1386 Starting airupnp version: v1.8.3 (Feb  1 2024 @ 01:10:50)
B[06:15:08.900] Start:1094 Binding to iface 192.168.2.198:0 [eth0]
B[06:15:08.902] Start:1133 Starting pico HTTP server on port 37663
h[06:15:18.734] AddMRDevice:1020 [0xb2f4a008]: adding renderer (小爱音箱-1969) with mac BBBB671C2D57
A[06:15:18.745] MasterHandler:638 [0xb2f4a008]: subscribe success
3[06:51:10.688] HandleRAOP:285 [0xb2f4a008]: Stream
>[06:51:10.705] HandleRAOP:353 [0xb2f4a008]: Volume[0..100] 33
>[06:51:10.723] HandleRAOP:353 [0xb2f4a008]: Volume[0..100] 34
m[06:51:11.052] HandleRAOP:320 [0xb2f4a008]: uPNP setURI http://192.168.2.198:57285/stream-0.wav (cookie 0x2)
<[06:51:14.453] ActionHandler:514 [0xb2f4a008]: uPNP playing
A[06:52:12.060] http_send:1133 HTTP send() error:HTTP/1.0 200 OK
Server: HairTunes
Content-Type: audio/wav
Connection: close

 4294967295 (strlen=82)
1[06:52:41.834] HandleRAOP:290 [0xb2f4a008]: Stop
<[06:52:42.314] ActionHandler:510 [0xb2f4a008]: uPNP stopped
```

Meanwhile, in order to check whether the website could be opened or not, I tried to access it via my computer browser. But I found that it took a very long time to load, and the player showed 0:00 and was unable to play. I also put this URL, which is http://192.168.2.198:57285/stream-0.wav, into Pot Player to try, and still there was no content. My phone is running iOS 18.2,using AM.

**Comment by pwt** [comment] 2024-12-23 16:09
Hi -- what speaker (or other audio device) are you sending audio to? It looks like the device is closing the connection.

Also, could you try starting the container with `-e CODEC='mp3:320'`, in case it's an issue playing WAV format.

**Comment by hyyczz** [comment] 2024-12-24 07:58
> Hi -- what speaker (or other audio device) are you sending audio to? It looks like the device is closing the connection.
> 
> Also, could you try starting the container with `-e CODEC='mp3:320'`, in case it's an issue playing WAV format.

I'm using this one:https://www.mi.com/global/product/mi-smart-speaker/
Great! It works well when starting the container with -e CODEC='mp3:320', although it might have some latency, about 4 sec.
Would it be possible to use a better format? such as Flac or AAC format?
Thank you again!

- [ ] [ ] [07:53:04.203] AddMRDevice:1020 [0xb2f55008]: adding renderer (小爱音箱-1969) with mac BBBB671C2D57
- [ ] [ ] [07:53:04.216] MasterHandler:638 [0xb2f55008]: subscribe success
- [ ] [ ] [07:53:08.449] HandleRAOP:285 [0xb2f55008]: Stream
- [ ] [ ] [07:53:08.465] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 33
- [ ] [ ] [07:53:08.473] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 33
- [ ] [ ] [07:53:11.075] HandleRAOP:320 [0xb2f55008]: uPNP setURI http://192.168.2.237:36761/stream-0.mp3 (cookie 0x2)
- [ ] [ ] [07:53:14.212] ActionHandler:514 [0xb2f55008]: uPNP playing
- [ ] [ ] [07:53:24.524] HandleRAOP:290 [0xb2f55008]: Stop
- [ ] [ ] [07:53:24.971] ActionHandler:510 [0xb2f55008]: uPNP stopped

**Comment by hyyczz** [comment] 2024-12-24 08:08
There is a playback delay, and sometimes it's so long that after I click the "Play" button on my mobile phone, there's still no sound from the speaker even after a long time. What's worse, sometimes I can't wait any longer and click the "Pause" button, and then the sound comes out. 
= =、、

[08:00:32.999] HandleRAOP:320 [0xb2f55008]: uPNP setURI http://192.168.2.237:40779/stream-2.mp3 (cookie 0x95)
[08:00:34.114] ActionHandler:514 [0xb2f55008]: uPNP playing
[08:01:07.291] HandleRAOP:290 [0xb2f55008]: Stop
[08:01:07.857] ActionHandler:510 [0xb2f55008]: uPNP stopped
[08:01:16.233] HandleRAOP:285 [0xb2f55008]: Stream
[08:01:16.238] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 33
[08:01:16.247] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 33
[08:01:16.553] HandleRAOP:320 [0xb2f55008]: uPNP setURI http://192.168.2.237:36809/stream-3.mp3 (cookie 0xdd)
[08:01:18.148] ActionHandler:514 [0xb2f55008]: uPNP playing
[08:01:40.988] _buffer_get_frame:847 [0x956640]: Buffer overrun 3066
[08:01:54.606] HandleRAOP:290 [0xb2f55008]: Stop
[08:01:55.142] ActionHandler:510 [0xb2f55008]: uPNP stopped
[08:04:45.289] HandleRAOP:285 [0xb2f55008]: Stream
[08:04:45.295] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 33
[08:04:45.306] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 33
[08:04:54.655] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 6
[08:04:54.806] HandleRAOP:320 [0xb2f55008]: uPNP setURI http://192.168.2.237:39791/stream-4.mp3 (cookie 0x12c)
[08:04:55.402] ActionHandler:514 [0xb2f55008]: uPNP playing
[08:05:29.427] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 8
[08:05:29.437] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 9
[08:05:29.443] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 10
[08:05:29.450] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 12
[08:05:29.457] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 13
[08:05:29.463] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 15
[08:05:29.472] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 16
[08:05:29.479] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 17
[08:05:29.488] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 18
[08:05:29.504] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 19
[08:05:29.537] HandleRAOP:353 [0xb2f55008]: Volume[0..100] 20
[08:05:41.549] _buffer_get_frame:847 [0x407580]: Buffer overrun 5861

**Comment by pwt** [comment] 2024-12-26 11:39
> It works well when starting the container with -e CODEC='mp3:320', although it might have some latency, about 4 sec. Would it be possible to use a better format? such as Flac or AAC format?

Good -- that confirmed that the WAV encoding format was the issue.
To use FLAC encoding: `-e CODEC='flc'`. This change will reduce the latency.

You can also experiment with the buffering durations to reduce delays. The default buffering is 1s on the input side and 1s on the output side, a total of 2s. To reduce this to 500ms for each of input and output:

`-e LATENCY='500:500:f'`

**Comment by hyyczz** [comment] 2024-12-27 01:40
> 

> > It works well when starting the container with -e CODEC='mp3:320', although it might have some latency, about 4 sec. Would it be possible to use a better format? such as Flac or AAC format?
> 
> Good -- that confirmed that the WAV encoding format was the issue. To use FLAC encoding: `-e CODEC='flc'`. This change will reduce the latency.
> 
> You can also experiment with the buffering durations to reduce delays. The default buffering is 1s on the input side and 1s on the output side, a total of 2s. To reduce this to 500ms for each of input and output:
> 
> `-e LATENCY='500:500:f'`

Work very well! Thank you ~

**Closed as completed** 2024-12-27 09:37 UTC
